projects:
  dormrate:
    schemaPath: amplify/backend/api/dormrate/build/schema.graphql
    includes:
      - queries
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
        region: us-east-2
        apiId: null
        maxDepth: 2
