projects:
  dormrate-dev:
    schemaPath: src/graphql/schema.json
    includes:
      - schema
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
        region: us-east-2
        apiId: egc3htyngjhxjhpwuooz5x6xge
        maxDepth: 2
extensions:
  amplify:
    version: 3
